dsn: "postgres://postgres:postgres@localhost:5432/go_restful?sslmode=disable"
server_port: 8989

storage:
  provider: "r2"
  bucket: "my-photos-saglix"
  account_id: "9987a005b28d7f8808e10116d5af5cda"
  prefix: "uploads/"